nelmio_api_doc:
  type_info: false
  use_validation_groups: false
  cache:
    pool: null
    item_id: null
  documentation:
    info:
      title: 'Reminder API'
      description: 'Documentación de la API de recordatorios'
      version: '1.0.0'
  media_types:
    - json
  html_config:
    assets_mode: cdn
    swagger_ui_config: [ ]
    redocly_config: [ ]
    stoplight_config: [ ]
  areas:
    path_patterns:
      - ^/api(?!/doc$)  # Captura todas las rutas /api excepto /api/doc
    host_patterns: [ ]