controllers:
    resource:
        path: ../src/Infrastructure/Controller/
        namespace: App\Infrastructure\Controller
    type: attribute

api_prueba:
    path: /api/prueba
    controller: App\Infrastructure\Controller\PruebaController::index
    methods: GET