name: First workflow
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php-versions: ['8.2', '8.3', '8.4']
    name: ${{ matrix.os }} PHP ${{ matrix.php-versions }}

    steps:
      - uses: actions/checkout@v2

      - name: Hello jfarinos
        run: echo "Hello world from ${{ github.workflow }} triggered by the ${{ github.event_name }}" done by ${{ github.actor}}

      - name: 😊 More and more
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "Job Context: $JOB_CONTEXT"
          echo "Done!"

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install dependencies
        run: composer install --ignore-platform-reqs

      - name: Run the tests
        run: composer phpunit
