name: First workflow
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Hello jfarinos
        run: echo "Hello world from ${{ github.workflow }} triggered by the ${{ github.event_name }}" done by ${{ github.actor}}